spring:
  application:
    name: Campus-Electricity
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/campus_electricity?timezone=Asia/Shanghai
    username: hydrocarbon
    password: 1352467890
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/campus_electricity?timezone=Asia/Shanghai
      username: hydrocarbon
      password: 1352467890
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      keepalive-time: 300000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 20
      health-check-properties:
        initialization-fail-timeout: 1
      pool-name: HikariPool
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
